# Generated by Django 3.0.2 on 2020-06-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название сайта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('mail', models.CharField(max_length=200, verbose_name='Email')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Параметры сайта',
                'verbose_name_plural': 'Параметры сайта',
                'db_table': 'Site Settings',
            },
        ),
    ]
