# Generated by Django 3.0.2 on 2020-06-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название сайта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Телефон'),
        ),
    ]
