# Generated by Django 3.0.7 on 2020-06-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluminiumradiator',
            name='width',
            field=models.CharField(default='', max_length=500, verbose_name='Ширина мм (Колическтво секций)'),
        ),
        migrations.AlterField(
            model_name='bimetalradiator',
            name='width',
            field=models.CharField(default='', max_length=500, verbose_name='Ширина мм (Колическтво секций)'),
        ),
        migrations.AlterField(
            model_name='steelpanelradiator',
            name='width',
            field=models.CharField(default='', max_length=500, verbose_name='Ширина мм (Колическтво секций)'),
        ),
        migrations.AlterField(
            model_name='steeltubularkztoradiator',
            name='length',
            field=models.CharField(default='', max_length=500, verbose_name='Длина прибора мм (Колическтво секций)'),
        ),
        migrations.AlterField(
            model_name='steeltubularradiator',
            name='width',
            field=models.CharField(default='', max_length=500, verbose_name='Ширина мм (Колическтво секций)'),
        ),
    ]
