# Generated by Django 3.0.2 on 2020-05-09 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_steelpanelradiator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип прибора',
                'verbose_name_plural': 'Типы прибора',
                'db_table': 'ApplianceType',
            },
        ),
        migrations.CreateModel(
            name='SteelTubularRadiator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=400, verbose_name='Модель')),
                ('height', models.IntegerField(verbose_name='Высота')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('depth', models.IntegerField(verbose_name='Глубина')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='steel_tubular_images', verbose_name='Картинка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('power', models.CharField(max_length=120, verbose_name='Мощность (50 / 60 / 70)')),
                ('pressure', models.IntegerField(verbose_name='Рабочее давление')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('connection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ConnectionType', verbose_name='Тип подключения')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Стальной трубчатый радиатор',
                'verbose_name_plural': 'Стальные трубчатые радиаторы',
                'db_table': 'Steel Tubular Radiator',
            },
        ),
        migrations.CreateModel(
            name='SteelTubularKZTORadiator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=400, verbose_name='Модель')),
                ('length', models.IntegerField(verbose_name='Длинна прибора')),
                ('mounting_size', models.IntegerField(verbose_name='Монтажный размер')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='steel_tubular_images', verbose_name='Картинка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('power', models.CharField(max_length=120, verbose_name='Мощность (70)')),
                ('pressure', models.IntegerField(verbose_name='Рабочее давление')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('appliance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ApplianceType', verbose_name='Тип прибора')),
                ('connection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ConnectionType', verbose_name='Тип подключения')),
            ],
            options={
                'verbose_name': 'Стальной трубчатый радиатор фирмы KZTO',
                'verbose_name_plural': 'Стальные трубчатые радиаторы фирмы KZTO',
                'db_table': 'Steel Tubular KZTO Radiator',
            },
        ),
    ]
