# Generated by Django 3.0.2 on 2020-05-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_appliancetype_steeltubularkztoradiator_steeltubularradiator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steeltubularkztoradiator',
            name='length',
            field=models.IntegerField(verbose_name='Длина прибора'),
        ),
    ]
