# Generated by Django 3.0.2 on 2020-05-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200509_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='steeltubularkztoradiator',
            name='manufacturer_country',
            field=models.CharField(default='Россия', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='steeltubularkztoradiator',
            name='manufacturer_name',
            field=models.CharField(default='KZTO', editable=False, max_length=100),
        ),
    ]
