# Generated by Django 3.0.2 on 2020-05-18 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_convectortype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='manufacturers_description_images', verbose_name='Картинка')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Описание производителя',
                'verbose_name_plural': 'Описания производителей',
                'db_table': 'Manufacturer Description',
            },
        ),
        migrations.CreateModel(
            name='RadiatorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип радиатора',
                'verbose_name_plural': 'Типы радиаторов',
                'db_table': 'Radiator Type',
            },
        ),
        migrations.AlterField(
            model_name='costironradiator',
            name='manufacturer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.Manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='designradiator',
            name='manufacturer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.Manufacturer', verbose_name='Производитель'),
        ),
        migrations.DeleteModel(
            name='CostIronManufacturer',
        ),
        migrations.DeleteModel(
            name='DesignManufacturer',
        ),
        migrations.AddField(
            model_name='manufacturerdescription',
            name='radiator_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.RadiatorType', verbose_name='Тип радиатора'),
        ),
    ]
