# Generated by Django 3.0.2 on 2020-05-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200518_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerdescription',
            name='radiator_type',
            field=models.IntegerField(choices=[(1, 'Дизайн радиаторы'), (2, 'Чугунные радиаторы'), (3, 'Встраиваемые конвекторы'), (4, 'Напольные конвекторы'), (5, 'Настенные конвекторы')], default=1, verbose_name='Тип радиоторов'),
        ),
        migrations.DeleteModel(
            name='RadiatorType',
        ),
    ]
