# Generated by Django 3.0.2 on 2020-05-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_floorconvector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConvectorType',
        ),
    ]
