# Generated by Django 3.0.2 on 2020-05-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_wallconvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatticeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип решетки',
                'verbose_name_plural': 'Типы решеток',
                'db_table': 'Lattice Type',
            },
        ),
        migrations.CreateModel(
            name='RecessedConvectorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Модель встаиваемого конвектора',
                'verbose_name_plural': 'Модели встаиваемых конвекторов',
                'db_table': 'Recessed Convector Model',
            },
        ),
        migrations.CreateModel(
            name='SideType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип бортика',
                'verbose_name_plural': 'Типы бортика',
                'db_table': 'Side Type',
            },
        ),
        migrations.CreateModel(
            name='RecessedConvector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(verbose_name='Высота')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='wall_convector_images', verbose_name='Картинка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('temperature', models.FloatField(verbose_name='Максимальная рабочая температура')),
                ('pressure', models.FloatField(verbose_name='Максимальное рабочее давление')),
                ('heat_output', models.FloatField(verbose_name='Выход тепла')),
                ('surface_temperature', models.FloatField(verbose_name='Максимальная температура поверхности')),
                ('connection', models.CharField(max_length=200, verbose_name='Подключение')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('connection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ConnectionType', verbose_name='Тип подключения')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Manufacturer', verbose_name='Производитель')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.RecessedConvectorModel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Встраиваемый конвектор',
                'verbose_name_plural': 'Встраиваемые конвекторы',
                'db_table': 'Recessed Convector',
            },
        ),
    ]
