# Generated by Django 3.0.2 on 2020-05-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_latticetype_recessedconvector_recessedconvectormodel_sidetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='recessedconvector',
            name='lattice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.LatticeType', verbose_name='Тип решетки'),
        ),
        migrations.AddField(
            model_name='recessedconvector',
            name='lattice_type',
            field=models.FloatField(blank=True, default=None, verbose_name='Шаг ламелей решетки, мм'),
        ),
        migrations.AddField(
            model_name='recessedconvector',
            name='metal_thickness',
            field=models.FloatField(blank=True, default=None, verbose_name='Толщина меттала, мм'),
        ),
        migrations.AddField(
            model_name='recessedconvector',
            name='presence_of_ribs',
            field=models.CharField(blank=True, default=None, max_length=300, verbose_name='Наличие ребер жесткости'),
        ),
        migrations.AddField(
            model_name='recessedconvector',
            name='side',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.SideType', verbose_name='Тип бортика'),
        ),
        migrations.AlterField(
            model_name='recessedconvector',
            name='connection',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Подключение'),
        ),
        migrations.AlterField(
            model_name='recessedconvector',
            name='heat_output',
            field=models.FloatField(blank=True, default=None, verbose_name='Выход тепла'),
        ),
        migrations.AlterField(
            model_name='recessedconvector',
            name='pressure',
            field=models.FloatField(blank=True, default=None, verbose_name='Максимальное рабочее давление'),
        ),
        migrations.AlterField(
            model_name='recessedconvector',
            name='surface_temperature',
            field=models.FloatField(blank=True, default=None, verbose_name='Максимальная температура поверхности'),
        ),
        migrations.AlterField(
            model_name='recessedconvector',
            name='temperature',
            field=models.FloatField(blank=True, default=None, verbose_name='Максимальная рабочая температура'),
        ),
    ]
