# Generated by Django 3.0.2 on 2020-05-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200528_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recessedconvector',
            name='height',
            field=models.IntegerField(verbose_name='Высота, мм'),
        ),
        migrations.AlterField(
            model_name='recessedconvector',
            name='length',
            field=models.IntegerField(verbose_name='Единица длинны, мм'),
        ),
        migrations.AlterField(
            model_name='recessedconvector',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена за единицу длинны'),
        ),
        migrations.AlterField(
            model_name='recessedconvector',
            name='width',
            field=models.IntegerField(verbose_name='Ширина, мм'),
        ),
    ]
