# Generated by Django 3.0.2 on 2020-05-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200528_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recessedconvector',
            name='length',
        ),
        migrations.AddField(
            model_name='recessedconvector',
            name='length_unit',
            field=models.IntegerField(default=None, verbose_name='Единица длинны, мм'),
        ),
        migrations.AddField(
            model_name='recessedconvector',
            name='max_length',
            field=models.IntegerField(default=None, verbose_name='Минимальная длинна, мм'),
        ),
        migrations.AddField(
            model_name='recessedconvector',
            name='min_length',
            field=models.IntegerField(default=None, verbose_name='Минимальная длинна, мм'),
        ),
    ]
