# Generated by Django 3.0.2 on 2020-05-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20200528_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recessedconvector',
            name='connection',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Подключение'),
        ),
        migrations.AlterField(
            model_name='recessedconvector',
            name='heat_output',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Выход тепла'),
        ),
        migrations.AlterField(
            model_name='recessedconvector',
            name='lattice_type',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Шаг ламелей решетки, мм'),
        ),
        migrations.AlterField(
            model_name='recessedconvector',
            name='metal_thickness',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Толщина меттала, мм'),
        ),
        migrations.AlterField(
            model_name='recessedconvector',
            name='presence_of_ribs',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Наличие ребер жесткости'),
        ),
        migrations.AlterField(
            model_name='recessedconvector',
            name='pressure',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Максимальное рабочее давление'),
        ),
        migrations.AlterField(
            model_name='recessedconvector',
            name='surface_temperature',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Максимальная температура поверхности'),
        ),
        migrations.AlterField(
            model_name='recessedconvector',
            name='temperature',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Максимальная рабочая температура'),
        ),
    ]
