# Generated by Django 3.0.2 on 2020-05-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20200528_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recessedconvectormodel',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
    ]
