# Generated by Django 3.0.2 on 2020-06-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20200528_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recessedconvector',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='wall_convector_images', verbose_name='Картинка вид сверху'),
        ),
    ]
