# Generated by Django 3.0.2 on 2020-06-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20200602_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='recessedconvector',
            name='main_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='wall_convector_images', verbose_name='Общая картинка (вид в профиль)'),
        ),
    ]
